input {
  file {
    path => "/var/log/remotos/*/auth.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    type => "auth"
  }

  file {
    path => "/var/log/remotos/*/syslog.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    type => "syslog"
  }
}

filter {
  mutate {
    add_field => { "environment" => "laboratorio-seguridad" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "siem-%{type}-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }
}